//
//  PCContact.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class PCContact: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _contactId: String?
    var _address: [String: String]?
    var _company: String?
    var _createdOn: NSNumber?
    var _email: [String: String]?
    var _firstName: String?
    var _geohash: String?
    var _imageUrl: String?
    var _lastName: String?
    var _modifiedOn: NSNumber?
    var _phone: [String: String]?
    
    class func dynamoDBTableName() -> String {

        return "demopasscode-mobilehub-1983560859-PCContact"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_contactId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_contactId" : "contactId",
               "_address" : "address",
               "_company" : "company",
               "_createdOn" : "createdOn",
               "_email" : "email",
               "_firstName" : "firstName",
               "_geohash" : "geohash",
               "_imageUrl" : "imageUrl",
               "_lastName" : "lastName",
               "_modifiedOn" : "modifiedOn",
               "_phone" : "phone",
        ]
    }
}
