//
//  User.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers class User: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _phone: String?
    var _password: String?
    
    class func dynamoDBTableName() -> String {
        
        return "demopasscode-mobilehub-1983560859-User"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_phone"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_phone" : "phone",
            "_password" : "password",
        ]
    }
}
